kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: 'dzhyunwei001@163.com'
      smtp_auth_username: 'dzhyunwei001@163.com'
      smtp_auth_password: 'dzh104029'
      slack_api_url: '<slack_api_url>'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 15m
      receiver: slack-notifications
      routes:
      - match:
          severity: email
        receiver: email_alert
    receivers:
    - name: 'email_alert'
      email_configs:
      - to: 'zhoukanggen@163.com'
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#alerts'
