apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /blog
    server: 10.9.219.148
